name: Weekly Impersonation Report

on:
    schedule:
        - cron: "0 0 * * *" # This will run the workflow every day at 00:00
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              env:
                  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
              run: npm i

            - name: Run workflow
              uses: mujo-code/puppeteer-headful@18.9.0
              with:
                  args: npm start --report
              env:
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
