name: Weekly Impersonation Report

on:
    schedule:
        - cron: "0 0 * * *" # This will run the workflow every day at 00:00
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install pnpm
              run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm

            - name: Install dependencies
              run: pnpm i

            - name: Run workflow
              run: pnpm start --report
              env:
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
